#!/bin/bash

hacerbackup() {
  clear
  echo "Haciendo copia de seguridad..."
  cd /etc/DTunnel
  #rm -r painelbackup > /dev/null
  #mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "painelbackup.zip guardado en /root"
  echo
  exit 0
}

autobackup() {
  clear
  read -p "¿Desea activar el Auto Backup? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Activando...."
    backmod
    echo
    echo "¡Copia de seguridad cada 5 horas activa!"
    exit 0
  }
  pmenu
}

removerpanel() {
  clear
  read -p "¿Desea eliminar el panel? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Eliminando..."
    poff
    rm /bin/pon /bin/poff /bin/pmenu /bin/backmod
    rm -r /etc/DTunnel
    echo "¡Eliminado con éxito!"
    exit 0
  }
  pmenu
}

restaurarbackup() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Archivo painelbackup.zip no encontrado en /root"
    sleep 4
    menuop
  }
  read -p "¿Desea Restaurar la Copia de Seguridad? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /etc/DTunnel
    rm prisma/database.db
    rm .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db /etc/DTunnel/prisma
    mv .env /etc/DTunnel
    cd /root
    rm -r painelbackup
    pon
    echo
    echo "¡Copia de seguridad restaurada con éxito!"
    exit 0
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Volviendo al menú"
    sleep 2
    pmenu
  }
  pmenu
}

#[[ ! -e /etc/DTunnel/src/index.ts ]] && exit 0

pmenu() {
  clear
  echo "Bienvenido/a al Panel DTunnel"
  echo 
  echo "1. Encender panel"
  echo "2. Reiniciar panel"
  echo "3. Apagar panel"
  echo "4. Hacer copia de seguridad"
  echo "5. Restaurar copia de seguridad"
  echo "6. Activar Auto backup"
  echo "7. Eliminar panel"
  echo "0. Salir"
  read -p "> " resp
  if [[ $resp = "1" ]]; then
    pon
    echo "¡Encendido con éxito!"
    sleep 3
    pmenu
  elif [[ $resp = "2" ]]; then
    clear
    pon
    echo "¡Reiniciado con éxito!"
    sleep 3
    pmenu
  elif [[ $resp = "3" ]]; then
    clear
    poff
    echo "¡Apagado con éxito!"
    sleep 3
    pmenu
  elif [[ $resp = "4" ]]; then
    hacerbackup
  elif [[ $resp = "5" ]]; then
    restaurarbackup
  elif [[ $resp = "6" ]]; then
    autobackup
  elif [[ $resp = "7" ]]; then
    removerpanel
  elif [[ $resp = "0" ]]; then
    echo "Saliendo..."
    exit 0
  else
    echo "¡Opción inválida!"
    sleep 3
    clear
    pmenu
  fi
}

pmenu
